### PR TITLE
run tests via tox before publishing to pypi

### PR DESCRIPTION
**Pull request by k-dominik**
added tox config for testing in a non-conda environment.

### CODE REVIEW

**Comment by oeway** [comment]
Hi @k-dominik Thanks for looking into this. Did you run pytest locally? 

It would be nice to still have a requirements.txt file with all the versions pined for testing with CI.

**Comment by k-dominik** [comment]
> Hi @k-dominik Thanks for looking into this. Did you run pytest locally?
> 
> It would be nice to still have a requirements.txt file with all the versions pined for testing with CI.

sure, I ran them locally. Why the pinning, Wei? I argue a single source of truth for deps. If we now start adding _another_ file, with different dependencies.... Also what's the purpose? Tox will use setup.py...

**Comment by oeway** [comment]
> > Hi @k-dominik Thanks for looking into this. Did you run pytest locally?
> > It would be nice to still have a requirements.txt file with all the versions pined for testing with CI.
> 
> sure, I ran them locally. Why the pinning, Wei? I argue a single source of truth for deps. If we now start adding _another_ file, with different dependencies.... Also what's the purpose? Tox will use setup.py...

@MartinHjelmare has more experiences in best practices for python projects, and recommended that to us for the ImJoy python projects (see [our template](https://github.com/imjoy-team/imjoy-python-template)). As I understand, pining all version in the requirements for CI testing is a recommended because it guarantees a stable and reproducible testing environment. E.g. we will save time in debugging if we have the exact test environment in the CI and locally, today and tomorrow etc. In general, we should not pin version in the setup.py, but for testing it's good to pin the versions.

**Comment by k-dominik** [comment]
I think that's overkill - especially with all those additional dependencies (that we don't even test via pip). It adds to maintenance burden and also to developers working on different environments than users see in production. I'd agree to test against something like this with a clear deployment target.

**Comment by oeway** [comment]
I will merge this for now!

We can continue discussion about whether we should pin, or delay it when we see issues related to that.

**Comment by k-dominik** [comment]
yeah let's discuss this in the next meeting.

**Pull request merged**
