### PR TITLE
Update pre-and-postprocessing

### PR DESCRIPTION
**Pull request by constantinpape**
Makes pre-and-postprocessing compatible with https://github.com/bioimage-io/spec-bioimage-io/blob/main/supported_formats_and_operations.md

TODO
- [x] pending #105 (changes in spec)
- [x] different output dtypes for pre and post, see https://github.com/bioimage-io/spec-bioimage-io/blob/main/supported_formats_and_operations.md
- [x] tests for dedicated postprocessing functions

### CODE REVIEW

**Comment by constantinpape** [comment]
It's also still unclear how to solve `reference_tensor` in the postprocessing, but we can leave that for a follow up PR to not block a release, as this might be a bit more complex.

**Comment by FynnBe** [comment]
a lot of the descripbed pre- and postprocessing is not yet specified in bioimageio.spec...

**Comment by constantinpape** [comment]
> a lot of the descripbed pre- and postprocessing is not yet specified in bioimageio.spec...

Not sure what you mean by this, but I take [this](https://github.com/bioimage-io/spec-bioimage-io/blob/main/supported_formats_and_operations.md) as the reference for pre/post, as it was discussed by everyone in Friday meetings. I have seen several models from deepimagej that need the changes here because they have used this as reference. If the python spec is not up-to-date with it that's an issue that should be fixed.

**Comment by FynnBe** [comment]
> Not sure what you mean by this, but I take this as the reference for pre/post, as it was discussed by everyone in Friday meetings. I have seen several models from deepimagej that need the changes here because they have used this as reference. If the python spec is not up-to-date with it that's an issue that should be fixed.

yes, it's missing in the bioimageio.spec implementation. I'm working on a PR...

**Comment by constantinpape** [comment]
I updated the post-processing now to ensure the correct output dtype. This is good to go from my side.

**Review by FynnBe — APPROVED** [review]
👍

**Pull request merged**
