### PR TITLE
Add JSON schema script

### PR DESCRIPTION
**Pull request by FynnBe**
starting point for https://github.com/bioimage-io/python-bioimage-io/issues/27

### CODE REVIEW

**Comment by oeway** [comment]
Great, I just pasted the schema to [here](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhdXRob3JzIjpbXSwib3B0aW9uYWxfa3dhcmdzIjp7fSwicHJlZGljdGlvbiI6eyJ3ZWlnaHRzIjp7Imhhc2giOnt9fX0sInRyYWluaW5nIjp7Im9wdGlvbmFsX2t3YXJncyI6e30sInNldHVwIjp7Im9wdGltaXplciI6eyJvcHRpb25hbF9rd2FyZ3MiOnt9fX19LCJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCJ9LCJzY2hlbWEiOnsiJHNjaGVtYSI6Imh0dHA6Ly9qc29uLXNjaGVtYS5vcmcvZHJhZnQtMDcvc2NoZW1hIyIsImRlZmluaXRpb25zIjp7IkNpdGVFbnRyeSI6eyJyZXF1aXJlZCI6WyJ0ZXh0Il0sInByb3BlcnRpZXMiOnsiZG9pIjp7InRpdGxlIjoiZG9pIiwidHlwZSI6WyJzdHJpbmciLCJudWxsIl19LCJ0ZXh0Ijp7InRpdGxlIjoidGV4dCIsInR5cGUiOiJzdHJpbmcifSwidXJsIjp7InRpdGxlIjoidXJsIiwidHlwZSI6WyJzdHJpbmciLCJudWxsIl19fSwidHlwZSI6Im9iamVjdCIsImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZX0sIklucHV0QXJyYXkiOnsicmVxdWlyZWQiOlsiZGF0YV90eXBlIiwibmFtZSIsInNoYXBlIl0sInByb3BlcnRpZXMiOnsiYXhlcyI6eyJ0aXRsZSI6ImF4ZXMiLCJ0eXBlIjpbInN0cmluZyIsIm51bGwiXX0sImRhdGFfcmFuZ2UiOnsidHlwZSI6Imxpc3QifSwiZGF0YV90eXBlIjp7InRpdGxlIjoiZGF0YV90eXBlIiwidHlwZSI6InN0cmluZyJ9LCJuYW1lIjp7InRpdGxlIjoibmFtZSIsInR5cGUiOiJzdHJpbmcifSwic2hhcGUiOnsidHlwZSI6Im9iamVjdCIsIiRyZWYiOiIjL2RlZmluaXRpb25zL0lucHV0U2hhcGUifX0sInR5cGUiOiJvYmplY3QiLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2V9LCJJbnB1dFNoYXBlIjp7InJlcXVpcmVkIjpbIm1pbiIsInN0ZXAiXSwicHJvcGVydGllcyI6eyJtaW4iOnsidGl0bGUiOiJtaW4iLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0aXRsZSI6Im1pbiIsInR5cGUiOiJudW1iZXIiLCJmb3JtYXQiOiJpbnRlZ2VyIn19LCJzdGVwIjp7InRpdGxlIjoic3RlcCIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InRpdGxlIjoic3RlcCIsInR5cGUiOiJudW1iZXIiLCJmb3JtYXQiOiJpbnRlZ2VyIn19fSwidHlwZSI6Im9iamVjdCIsImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZX0sIk91dHB1dEFycmF5Ijp7InJlcXVpcmVkIjpbImRhdGFfdHlwZSIsIm5hbWUiLCJzaGFwZSJdLCJwcm9wZXJ0aWVzIjp7ImF4ZXMiOnsidGl0bGUiOiJheGVzIiwidHlwZSI6WyJzdHJpbmciLCJudWxsIl19LCJkYXRhX3JhbmdlIjp7InR5cGUiOiJsaXN0In0sImRhdGFfdHlwZSI6eyJ0aXRsZSI6ImRhdGFfdHlwZSIsInR5cGUiOiJzdHJpbmcifSwiaGFsbyI6eyJ0aXRsZSI6ImhhbG8iLCJ0eXBlIjpbImFycmF5IiwibnVsbCJdLCJpdGVtcyI6eyJ0aXRsZSI6ImhhbG8iLCJ0eXBlIjoibnVtYmVyIiwiZm9ybWF0IjoiaW50ZWdlciJ9fSwibmFtZSI6eyJ0aXRsZSI6Im5hbWUiLCJ0eXBlIjoic3RyaW5nIn0sInNoYXBlIjp7InR5cGUiOiJvYmplY3QiLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9PdXRwdXRTaGFwZSJ9fSwidHlwZSI6Im9iamVjdCIsImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZX0sIk91dHB1dFNoYXBlIjp7InJlcXVpcmVkIjpbIm9mZnNldCIsInNjYWxlIl0sInByb3BlcnRpZXMiOnsib2Zmc2V0Ijp7InRpdGxlIjoib2Zmc2V0IiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidGl0bGUiOiJvZmZzZXQiLCJ0eXBlIjoibnVtYmVyIiwiZm9ybWF0IjoiaW50ZWdlciJ9fSwicmVmZXJlbmNlX2lucHV0Ijp7InRpdGxlIjoicmVmZXJlbmNlX2lucHV0IiwidHlwZSI6WyJzdHJpbmciLCJudWxsIl19LCJzY2FsZSI6eyJ0aXRsZSI6InNjYWxlIiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidGl0bGUiOiJzY2FsZSIsInR5cGUiOiJudW1iZXIiLCJmb3JtYXQiOiJmbG9hdCJ9fX0sInR5cGUiOiJvYmplY3QiLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2V9LCJQcmVkaWN0aW9uIjp7InByb3BlcnRpZXMiOnsiZGVwZW5kZW5jaWVzIjp7InRpdGxlIjoiZGVwZW5kZW5jaWVzIiwidHlwZSI6WyJzdHJpbmciLCJudWxsIl19LCJwb3N0cHJvY2VzcyI6eyJ0eXBlIjpbImFycmF5IiwibnVsbCJdLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvVHJhbnNmb3JtYXRpb24ifX0sInByZXByb2Nlc3MiOnsidHlwZSI6WyJhcnJheSIsIm51bGwiXSwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsIiRyZWYiOiIjL2RlZmluaXRpb25zL1RyYW5zZm9ybWF0aW9uIn19LCJ3ZWlnaHRzIjp7InR5cGUiOiJvYmplY3QiLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9XZWlnaHRzIn19LCJ0eXBlIjoib2JqZWN0IiwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlfSwiVHJhbnNmb3JtYXRpb24iOnsicmVxdWlyZWQiOlsic3BlYyJdLCJwcm9wZXJ0aWVzIjp7Imt3YXJncyI6eyJ0aXRsZSI6Imt3YXJncyIsInR5cGUiOiJvYmplY3QifSwic3BlYyI6eyJ0eXBlIjoib2JqZWN0IiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvVHJhbnNmb3JtYXRpb25TcGVjIn19LCJ0eXBlIjoib2JqZWN0IiwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlfSwiVHJhbnNmb3JtYXRpb25TcGVjIjp7InJlcXVpcmVkIjpbImNpdGUiLCJkZXBlbmRlbmNpZXMiLCJkZXNjcmlwdGlvbiIsImRvY3VtZW50YXRpb24iLCJmb3JtYXRfdmVyc2lvbiIsImlucHV0cyIsImxhbmd1YWdlIiwibGljZW5zZSIsIm5hbWUiLCJvdXRwdXRzIiwic291cmNlIiwidGFncyJdLCJwcm9wZXJ0aWVzIjp7ImF1dGhvcnMiOnsidGl0bGUiOiJhdXRob3JzIiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidGl0bGUiOiJhdXRob3JzIiwidHlwZSI6InN0cmluZyJ9fSwiY2l0ZSI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvQ2l0ZUVudHJ5In19LCJjb3ZlcnMiOnsidGl0bGUiOiJjb3ZlcnMiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0aXRsZSI6ImNvdmVycyIsInR5cGUiOiJzdHJpbmcifX0sImRlcGVuZGVuY2llcyI6eyJ0aXRsZSI6ImRlcGVuZGVuY2llcyIsInR5cGUiOiJzdHJpbmcifSwiZGVzY3JpcHRpb24iOnsidGl0bGUiOiJkZXNjcmlwdGlvbiIsInR5cGUiOiJzdHJpbmcifSwiZG9jdW1lbnRhdGlvbiI6eyJ0aXRsZSI6ImRvY3VtZW50YXRpb24iLCJ0eXBlIjoic3RyaW5nIn0sImZvcm1hdF92ZXJzaW9uIjp7InRpdGxlIjoiZm9ybWF0X3ZlcnNpb24iLCJ0eXBlIjoic3RyaW5nIn0sImZyYW1ld29yayI6eyJ0aXRsZSI6ImZyYW1ld29yayIsInR5cGUiOlsic3RyaW5nIiwibnVsbCJdfSwiaW5wdXRzIjp7InR5cGUiOiJvYmplY3QiLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9JbnB1dEFycmF5In0sImxhbmd1YWdlIjp7InRpdGxlIjoibGFuZ3VhZ2UiLCJ0eXBlIjoic3RyaW5nIn0sImxpY2Vuc2UiOnsidGl0bGUiOiJsaWNlbnNlIiwidHlwZSI6InN0cmluZyJ9LCJuYW1lIjp7InRpdGxlIjoibmFtZSIsInR5cGUiOiJzdHJpbmcifSwib3B0aW9uYWxfa3dhcmdzIjp7InRpdGxlIjoib3B0aW9uYWxfa3dhcmdzIiwidHlwZSI6Im9iamVjdCJ9LCJvdXRwdXRzIjp7InR5cGUiOiJvYmplY3QiLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9PdXRwdXRBcnJheSJ9LCJyZXF1aXJlZF9rd2FyZ3MiOnsidGl0bGUiOiJyZXF1aXJlZF9rd2FyZ3MiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0aXRsZSI6InJlcXVpcmVkX2t3YXJncyIsInR5cGUiOiJzdHJpbmcifX0sInNvdXJjZSI6eyJ0aXRsZSI6InNvdXJjZSIsInR5cGUiOiJzdHJpbmcifSwidGFncyI6eyJ0aXRsZSI6InRhZ3MiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0aXRsZSI6InRhZ3MiLCJ0eXBlIjoic3RyaW5nIn19LCJ0ZXN0X2lucHV0Ijp7InRpdGxlIjoidGVzdF9pbnB1dCIsInR5cGUiOlsic3RyaW5nIiwibnVsbCJdfSwidGVzdF9vdXRwdXQiOnsidGl0bGUiOiJ0ZXN0X291dHB1dCIsInR5cGUiOlsic3RyaW5nIiwibnVsbCJdfX0sInR5cGUiOiJvYmplY3QiLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2V9LCJXZWlnaHRzIjp7InJlcXVpcmVkIjpbInNvdXJjZSJdLCJwcm9wZXJ0aWVzIjp7Imhhc2giOnsidGl0bGUiOiJoYXNoIiwidHlwZSI6Im9iamVjdCJ9LCJzb3VyY2UiOnsidGl0bGUiOiJzb3VyY2UiLCJ0eXBlIjoic3RyaW5nIn19LCJ0eXBlIjoib2JqZWN0IiwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlfSwiVHJhaW5pbmciOnsicmVxdWlyZWQiOlsiZGVwZW5kZW5jaWVzIiwic291cmNlIl0sInByb3BlcnRpZXMiOnsiZGVwZW5kZW5jaWVzIjp7InRpdGxlIjoiZGVwZW5kZW5jaWVzIiwidHlwZSI6InN0cmluZyJ9LCJkZXNjcmlwdGlvbiI6eyJ0aXRsZSI6ImRlc2NyaXB0aW9uIiwidHlwZSI6WyJzdHJpbmciLCJudWxsIl19LCJvcHRpb25hbF9rd2FyZ3MiOnsidGl0bGUiOiJvcHRpb25hbF9rd2FyZ3MiLCJ0eXBlIjoib2JqZWN0In0sInJlcXVpcmVkX2t3YXJncyI6eyJ0aXRsZSI6InJlcXVpcmVkX2t3YXJncyIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InRpdGxlIjoicmVxdWlyZWRfa3dhcmdzIiwidHlwZSI6InN0cmluZyJ9fSwic2V0dXAiOnsidHlwZSI6Im9iamVjdCIsIiRyZWYiOiIjL2RlZmluaXRpb25zL1NldHVwIn0sInNvdXJjZSI6eyJ0aXRsZSI6InNvdXJjZSIsInR5cGUiOiJzdHJpbmcifX0sInR5cGUiOiJvYmplY3QiLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2V9LCJTZXR1cCI6eyJyZXF1aXJlZCI6WyJzYW1wbGVycyJdLCJwcm9wZXJ0aWVzIjp7Imxvc3NlcyI6eyJ0eXBlIjpbImFycmF5IiwibnVsbCJdLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvVHJhbnNmb3JtYXRpb24ifX0sIm9wdGltaXplciI6eyJ0eXBlIjoib2JqZWN0IiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvT3B0aW1pemVyIn0sInBvc3Rwcm9jZXNzIjp7InR5cGUiOlsiYXJyYXkiLCJudWxsIl0sIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9UcmFuc2Zvcm1hdGlvbiJ9fSwicHJlcHJvY2VzcyI6eyJ0eXBlIjpbImFycmF5IiwibnVsbCJdLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvVHJhbnNmb3JtYXRpb24ifX0sInNhbXBsZXJzIjp7InRpdGxlIjoic2FtcGxlcnMiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvU2FtcGxlciJ9fX0sInR5cGUiOiJvYmplY3QiLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2V9LCJPcHRpbWl6ZXIiOnsicmVxdWlyZWQiOlsic291cmNlIl0sInByb3BlcnRpZXMiOnsib3B0aW9uYWxfa3dhcmdzIjp7InRpdGxlIjoib3B0aW9uYWxfa3dhcmdzIiwidHlwZSI6Im9iamVjdCJ9LCJyZXF1aXJlZF9rd2FyZ3MiOnsidGl0bGUiOiJyZXF1aXJlZF9rd2FyZ3MiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0aXRsZSI6InJlcXVpcmVkX2t3YXJncyIsInR5cGUiOiJzdHJpbmcifX0sInNvdXJjZSI6eyJ0aXRsZSI6InNvdXJjZSIsInR5cGUiOiJzdHJpbmcifX0sInR5cGUiOiJvYmplY3QiLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2V9LCJTYW1wbGVyIjp7InJlcXVpcmVkIjpbInJlYWRlcnMiXSwicHJvcGVydGllcyI6eyJrd2FyZ3MiOnsidGl0bGUiOiJrd2FyZ3MiLCJ0eXBlIjoib2JqZWN0In0sInJlYWRlcnMiOnsidGl0bGUiOiJyZWFkZXJzIiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsIiRyZWYiOiIjL2RlZmluaXRpb25zL1JlYWRlciJ9fSwic3BlYyI6eyJ0eXBlIjoib2JqZWN0IiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvU2FtcGxlclNwZWMifX0sInR5cGUiOiJvYmplY3QiLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2V9LCJSZWFkZXIiOnsicHJvcGVydGllcyI6eyJrd2FyZ3MiOnsidGl0bGUiOiJrd2FyZ3MiLCJ0eXBlIjoib2JqZWN0In0sInNwZWMiOnsidHlwZSI6Im9iamVjdCIsIiRyZWYiOiIjL2RlZmluaXRpb25zL1JlYWRlclNwZWMifSwidHJhbnNmb3JtYXRpb25zIjp7InRpdGxlIjoidHJhbnNmb3JtYXRpb25zIiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsIiRyZWYiOiIjL2RlZmluaXRpb25zL1RyYW5zZm9ybWF0aW9uIn19fSwidHlwZSI6Im9iamVjdCIsImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZX0sIlJlYWRlclNwZWMiOnsicmVxdWlyZWQiOlsiY2l0ZSIsImRlc2NyaXB0aW9uIiwiZG9jdW1lbnRhdGlvbiIsImZvcm1hdF92ZXJzaW9uIiwibGFuZ3VhZ2UiLCJsaWNlbnNlIiwibmFtZSIsIm91dHB1dHMiLCJzb3VyY2UiLCJ0YWdzIl0sInByb3BlcnRpZXMiOnsiYXV0aG9ycyI6eyJ0aXRsZSI6ImF1dGhvcnMiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0aXRsZSI6ImF1dGhvcnMiLCJ0eXBlIjoic3RyaW5nIn19LCJjaXRlIjp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9DaXRlRW50cnkifX0sImNvdmVycyI6eyJ0aXRsZSI6ImNvdmVycyIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InRpdGxlIjoiY292ZXJzIiwidHlwZSI6InN0cmluZyJ9fSwiZGVwZW5kZW5jaWVzIjp7InRpdGxlIjoiZGVwZW5kZW5jaWVzIiwidHlwZSI6WyJzdHJpbmciLCJudWxsIl19LCJkZXNjcmlwdGlvbiI6eyJ0aXRsZSI6ImRlc2NyaXB0aW9uIiwidHlwZSI6InN0cmluZyJ9LCJkb2N1bWVudGF0aW9uIjp7InRpdGxlIjoiZG9jdW1lbnRhdGlvbiIsInR5cGUiOiJzdHJpbmcifSwiZm9ybWF0X3ZlcnNpb24iOnsidGl0bGUiOiJmb3JtYXRfdmVyc2lvbiIsInR5cGUiOiJzdHJpbmcifSwiZnJhbWV3b3JrIjp7InRpdGxlIjoiZnJhbWV3b3JrIiwidHlwZSI6WyJzdHJpbmciLCJudWxsIl19LCJsYW5ndWFnZSI6eyJ0aXRsZSI6Imxhbmd1YWdlIiwidHlwZSI6InN0cmluZyJ9LCJsaWNlbnNlIjp7InRpdGxlIjoibGljZW5zZSIsInR5cGUiOiJzdHJpbmcifSwibmFtZSI6eyJ0aXRsZSI6Im5hbWUiLCJ0eXBlIjoic3RyaW5nIn0sIm9wdGlvbmFsX2t3YXJncyI6eyJ0aXRsZSI6Im9wdGlvbmFsX2t3YXJncyIsInR5cGUiOiJvYmplY3QifSwib3V0cHV0cyI6eyJ0eXBlIjoib2JqZWN0IiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvT3V0cHV0QXJyYXkifSwicmVxdWlyZWRfa3dhcmdzIjp7InRpdGxlIjoicmVxdWlyZWRfa3dhcmdzIiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidGl0bGUiOiJyZXF1aXJlZF9rd2FyZ3MiLCJ0eXBlIjoic3RyaW5nIn19LCJzb3VyY2UiOnsidGl0bGUiOiJzb3VyY2UiLCJ0eXBlIjoic3RyaW5nIn0sInRhZ3MiOnsidGl0bGUiOiJ0YWdzIiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidGl0bGUiOiJ0YWdzIiwidHlwZSI6InN0cmluZyJ9fSwidGVzdF9pbnB1dCI6eyJ0aXRsZSI6InRlc3RfaW5wdXQiLCJ0eXBlIjpbInN0cmluZyIsIm51bGwiXX0sInRlc3Rfb3V0cHV0Ijp7InRpdGxlIjoidGVzdF9vdXRwdXQiLCJ0eXBlIjpbInN0cmluZyIsIm51bGwiXX19LCJ0eXBlIjoib2JqZWN0IiwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlfSwiU2FtcGxlclNwZWMiOnsicmVxdWlyZWQiOlsiY2l0ZSIsImRlc2NyaXB0aW9uIiwiZG9jdW1lbnRhdGlvbiIsImZvcm1hdF92ZXJzaW9uIiwibGFuZ3VhZ2UiLCJsaWNlbnNlIiwibmFtZSIsInNvdXJjZSIsInRhZ3MiXSwicHJvcGVydGllcyI6eyJhdXRob3JzIjp7InRpdGxlIjoiYXV0aG9ycyIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InRpdGxlIjoiYXV0aG9ycyIsInR5cGUiOiJzdHJpbmcifX0sImNpdGUiOnsidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsIiRyZWYiOiIjL2RlZmluaXRpb25zL0NpdGVFbnRyeSJ9fSwiY292ZXJzIjp7InRpdGxlIjoiY292ZXJzIiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidGl0bGUiOiJjb3ZlcnMiLCJ0eXBlIjoic3RyaW5nIn19LCJkZXBlbmRlbmNpZXMiOnsidGl0bGUiOiJkZXBlbmRlbmNpZXMiLCJ0eXBlIjpbInN0cmluZyIsIm51bGwiXX0sImRlc2NyaXB0aW9uIjp7InRpdGxlIjoiZGVzY3JpcHRpb24iLCJ0eXBlIjoic3RyaW5nIn0sImRvY3VtZW50YXRpb24iOnsidGl0bGUiOiJkb2N1bWVudGF0aW9uIiwidHlwZSI6InN0cmluZyJ9LCJmb3JtYXRfdmVyc2lvbiI6eyJ0aXRsZSI6ImZvcm1hdF92ZXJzaW9uIiwidHlwZSI6InN0cmluZyJ9LCJmcmFtZXdvcmsiOnsidGl0bGUiOiJmcmFtZXdvcmsiLCJ0eXBlIjpbInN0cmluZyIsIm51bGwiXX0sImxhbmd1YWdlIjp7InRpdGxlIjoibGFuZ3VhZ2UiLCJ0eXBlIjoic3RyaW5nIn0sImxpY2Vuc2UiOnsidGl0bGUiOiJsaWNlbnNlIiwidHlwZSI6InN0cmluZyJ9LCJuYW1lIjp7InRpdGxlIjoibmFtZSIsInR5cGUiOiJzdHJpbmcifSwib3B0aW9uYWxfa3dhcmdzIjp7InRpdGxlIjoib3B0aW9uYWxfa3dhcmdzIiwidHlwZSI6Im9iamVjdCJ9LCJvdXRwdXRzIjp7InR5cGUiOiJvYmplY3QiLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9PdXRwdXRBcnJheSJ9LCJyZXF1aXJlZF9rd2FyZ3MiOnsidGl0bGUiOiJyZXF1aXJlZF9rd2FyZ3MiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0aXRsZSI6InJlcXVpcmVkX2t3YXJncyIsInR5cGUiOiJzdHJpbmcifX0sInNvdXJjZSI6eyJ0aXRsZSI6InNvdXJjZSIsInR5cGUiOiJzdHJpbmcifSwidGFncyI6eyJ0aXRsZSI6InRhZ3MiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0aXRsZSI6InRhZ3MiLCJ0eXBlIjoic3RyaW5nIn19LCJ0ZXN0X2lucHV0Ijp7InRpdGxlIjoidGVzdF9pbnB1dCIsInR5cGUiOlsic3RyaW5nIiwibnVsbCJdfSwidGVzdF9vdXRwdXQiOnsidGl0bGUiOiJ0ZXN0X291dHB1dCIsInR5cGUiOlsic3RyaW5nIiwibnVsbCJdfX0sInR5cGUiOiJvYmplY3QiLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2V9LCJNb2RlbFNwZWMiOnsicmVxdWlyZWQiOlsiY2l0ZSIsImRlc2NyaXB0aW9uIiwiZG9jdW1lbnRhdGlvbiIsImZvcm1hdF92ZXJzaW9uIiwibGFuZ3VhZ2UiLCJsaWNlbnNlIiwibmFtZSIsInNvdXJjZSIsInRhZ3MiXSwicHJvcGVydGllcyI6eyJhdXRob3JzIjp7InRpdGxlIjoiYXV0aG9ycyIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InRpdGxlIjoiYXV0aG9ycyIsInR5cGUiOiJzdHJpbmcifX0sImNpdGUiOnsidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsIiRyZWYiOiIjL2RlZmluaXRpb25zL0NpdGVFbnRyeSJ9fSwiY292ZXJzIjp7InRpdGxlIjoiY292ZXJzIiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidGl0bGUiOiJjb3ZlcnMiLCJ0eXBlIjoic3RyaW5nIn19LCJkZXNjcmlwdGlvbiI6eyJ0aXRsZSI6ImRlc2NyaXB0aW9uIiwidHlwZSI6InN0cmluZyJ9LCJkb2N1bWVudGF0aW9uIjp7InRpdGxlIjoiZG9jdW1lbnRhdGlvbiIsInR5cGUiOiJzdHJpbmcifSwiZm9ybWF0X3ZlcnNpb24iOnsidGl0bGUiOiJmb3JtYXRfdmVyc2lvbiIsInR5cGUiOiJzdHJpbmcifSwiZnJhbWV3b3JrIjp7InRpdGxlIjoiZnJhbWV3b3JrIiwidHlwZSI6WyJzdHJpbmciLCJudWxsIl19LCJpbnB1dHMiOnsidHlwZSI6WyJhcnJheSIsIm51bGwiXSwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsIiRyZWYiOiIjL2RlZmluaXRpb25zL0lucHV0QXJyYXkifX0sImxhbmd1YWdlIjp7InRpdGxlIjoibGFuZ3VhZ2UiLCJ0eXBlIjoic3RyaW5nIn0sImxpY2Vuc2UiOnsidGl0bGUiOiJsaWNlbnNlIiwidHlwZSI6InN0cmluZyJ9LCJuYW1lIjp7InRpdGxlIjoibmFtZSIsInR5cGUiOiJzdHJpbmcifSwib3B0aW9uYWxfa3dhcmdzIjp7InRpdGxlIjoib3B0aW9uYWxfa3dhcmdzIiwidHlwZSI6Im9iamVjdCJ9LCJvdXRwdXRzIjp7InR5cGUiOlsiYXJyYXkiLCJudWxsIl0sIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9PdXRwdXRBcnJheSJ9fSwicHJlZGljdGlvbiI6eyJ0eXBlIjoib2JqZWN0IiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvUHJlZGljdGlvbiJ9LCJyZXF1aXJlZF9rd2FyZ3MiOnsidGl0bGUiOiJyZXF1aXJlZF9rd2FyZ3MiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0aXRsZSI6InJlcXVpcmVkX2t3YXJncyIsInR5cGUiOiJzdHJpbmcifX0sInNvdXJjZSI6eyJ0aXRsZSI6InNvdXJjZSIsInR5cGUiOiJzdHJpbmcifSwidGFncyI6eyJ0aXRsZSI6InRhZ3MiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0aXRsZSI6InRhZ3MiLCJ0eXBlIjoic3RyaW5nIn19LCJ0ZXN0X2lucHV0Ijp7InRpdGxlIjoidGVzdF9pbnB1dCIsInR5cGUiOlsic3RyaW5nIiwibnVsbCJdfSwidGVzdF9vdXRwdXQiOnsidGl0bGUiOiJ0ZXN0X291dHB1dCIsInR5cGUiOlsic3RyaW5nIiwibnVsbCJdfSwidHJhaW5pbmciOnsidHlwZSI6Im9iamVjdCIsIiRyZWYiOiIjL2RlZmluaXRpb25zL1RyYWluaW5nIn19LCJ0eXBlIjoib2JqZWN0IiwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlfX0sIiRyZWYiOiIjL2RlZmluaXRpb25zL01vZGVsU3BlYyJ9LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=), and it's nice that we will have a webform immediately.

The idea would be add a BioEngine App to generate the yaml file by filling a form.

**Comment by FynnBe** [comment]
We need to correct the mapping of the marshmallow Tuple field. My guess of 'list' didn't cut it apparently...

data_range
Unsupported field schema for field root_inputs_0_data_range: Unknown field type list.

{
  "type": "list"
}

**Comment by oeway** [comment]
CC @frauzufall , here is a WIP to generate a JSON schema, the idea is that we will host this schema on the model zoo website so others can pull it and validate the model yaml.

**Comment by oeway** [comment]
A gentle ping to @FynnBe , would be nice to get this one ready for the website.

**Pull request merged**
