### PR TITLE
Add bulk prediction script

### PR DESCRIPTION
**Pull request by constantinpape**
I needed a script to predict all images in a folder; it might make sense to add it here, as the current functionality in the predict script is fairly limited.

@FynnBe @k-dominik do you think this is something we want to add here? I personally find this very useful, but I am not sure if you want it to be maintained here; I could also add it to my dl repo.

### CODE REVIEW

**Comment by FynnBe** [comment]
IMO it makes sense to have it here. potentially by just expanding the predict script with some glob pattern... ?

**Comment by constantinpape** [comment]
> predict script with some glob pattern... ?

Yes, I also thought about that. 

It's a bit unfortunate that there is so much axis logic that needs to be introduced, but I am not sure if there's anything we could reuse here.

**Comment by constantinpape** [comment]
@FynnBe @k-dominik this is ready for review now. In this PR:
- Move all CLI functionality to `__main__.py`.
- Add different prediction modes:
  - single input
  - multiple input
  - with padding
  - with tiling

**Comment by FynnBe** [comment]
could we make the test_cli tests pass before merging?

**Review by FynnBe — APPROVED** [review]
👍

**Comment by constantinpape** [comment]
The CLI tests pass now; I replaced `conda develop` with `pip install -e`; looks like there is some issue with installing CLI otherwise.

**Pull request merged**
