### PR TITLE
Fix release script in CI

### PR DESCRIPTION
**Pull request by oeway**
@FynnBe Is it possible to have a pip only requirements file for running tests before releasing the package on PyPI?

### CODE REVIEW

**Comment by FynnBe** [comment]
afaik that should be possible

**Comment by oeway** [comment]
> afaik that should be possible

Great! Could you please make one?

**Comment by FynnBe** [comment]
> > afaik that should be possible
> 
> Great! Could you please make one?

Thanks to @k-dominik , who will take care of it :-)

**Comment by k-dominik** [comment]
I'm not sure I understood the issue but I opened a PR on top of your PR here: https://github.com/bioimage-io/python-bioimage-io/pull/111

**Pull request merged**
